trigger:

  batch: true
  branches:
    include:
      - '*'


pool:
  vmImage: 'macOS-12'


steps:

  - checkout: self
    clean: true # https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch
    fetchDepth: 0
    persistCredentials: true

  - task: Bash@3
    displayName: 'Setup Build Environment'
    inputs:
      filePath: 'Laerdal.Scripts/Laerdal.SetupBuildEnvironment.sh'
      arguments: ' "https://pkgs.dev.azure.com/LaerdalMedical/_packaging/LaerdalNuGet/nuget/v3/index.json"   "$(Laerdal.NugetFeed.Username)"   "$(Laerdal.NugetFeed.AccessToken)"  "$(Build.ArtifactStagingDirectory)" '
      targetType: 'filePath'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '$(Build.SourcesDirectory)/Laerdal.Scripts/Laerdal.Builder.targets'
      arguments: '--verbosity detailed'
      configuration: 'Release'

  - publish: '$(Build.ArtifactStagingDirectory)'
    artifact: 'output'
