trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: macOS-12

steps:
  - checkout: self
    clean: true
    #https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#shallow-fetch
    fetchDepth: 0
    persistCredentials: true

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'
    inputs:
      checkLatest: true

  - task: MSBuild@1
    displayName: MSBuild
    inputs:
      solution: Laerdal.Build.proj
      configuration: Release

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: output